authenticate/urls.py
from django.urls import path, include
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
]

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:print_id>', views.cart_add, name='cart_add'),
    path('remove/<str:print_id>', views.cart_remove, name='cart_remove'),
]

design_rox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf .urls.static import static
import print.views

admin.site.site_header = 'Designs By Rox Dicky Admin'
admin.site.site_title = 'Designs By Rox Dicky Admin'
admin.site.index_title = 'Designs By Rox Dicky Administration'



urlpatterns = [
    path('', print.views.home, name = 'home'),
    path('auth/', include('authenticate.urls', namespace='auth')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('print/', include('print.urls', namespace='print')),
    path('photo/', include('photo.urls')),
    path('wedding/', include('wedding.urls')),
    path('party/', include('party.urls')),
    path('business/', include('business.urls')),
    path('kid/', include('kid.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kid/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.kid, name = 'kid'),
]

design_rox/templates/base.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Bradley Theron for Designs By Rox Dicky">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>Designs by Rox Dicky</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/blog/">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
  <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
  <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
  <meta name="theme-color" content="#563d7c">


  <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet"> -->
  <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">

</head>
<body>
  <div class="container">

      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-2 pt-1">
            <img src="{% static 'images/rox_logo.png' %}" class="rounded-sm" height="100" width="100"  alt="logo">
          </div>
          <div class="col-6 text-center">
            <a class="blog-header-logo" href="{% url 'home' %}">Designs By Rox Dicky</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <!-- Your cart: -->
                    <a href="{% url "cart:cart_detail" %}">
                      <span class="badge badge-pill badge-primary">{{ total_items }}</span>
                         R{{ cart.get_total_price }}
                    </a>
                {% else %}
                    <span class="badge badge-pill badge-primary">0</span>
                {% endif %}
            {% endwith %}
            <div class="ml-2">
              {% if not user.is_authenticated %}
              <a href="{% url 'auth:login' %}">Login</a>
              <a href="{% url 'auth:register' %}">Register</a>
              {% else %}
              <a href="{% url 'auth:logout' %}">Logout</a>
              <a href="{% url 'auth:edit_profile' %}">Edit Profile</a>
              <a href="{% url 'auth:change_password' %}">Change Password</a>
              {% endif %}

            </div>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{% url 'kid' %}">Kids & Baby</a>
          <a class="p-2 text-muted" href="{% url 'wedding' %}">Wedding</a>
          <a class="p-2 text-muted" href="{% url 'party' %}">Party</a>
          <a class="p-2 text-muted" href="{% url 'business' %}">Business</a>
          <a class="p-2 text-muted" href="{% url 'photo_gallery' %}">Photo</a>
        </nav>
      </div>
      <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong></strong>{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endfor%}
        {% endif %}
      </div>

    {% block content %}

    {% endblock %}

    <footer>
      <div class="row">
        <div class="col-md-6 ml-auto">
          <ul class="footer-nav">
            <li><a href="#">Services</a></li>
            <li><a href="#">Kids & Baby</a></li>
            <li><a href="#">Wedings</a></li>
            <li><a href="#">Party</a></li>
            <li><a href="#">Photo</a></li>
          </ul>
        </div>
        <div class="col-md-6 mr-auto">
          <ul class="social-links">
            <li><a href="#"><ion-icon name="logo-facebook" size="large"></ion-icon></a></li>
            <li><a href="#"><ion-icon name="logo-twitter" size="large"></ion-icon></i></a></li>
            <li><a href="#"><ion-icon name="logo-instagram" size="large"></ion-icon></i></a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <p>
            This website was created for "Designs By Rox Dicky using HTML5 ,CSS3 and Django" by Bradley Theron. No copyrights here.<br>
            This webpage is for you! So go and do whatever you want with it and have fun.
          </p>
          <p>
            Build with <ion-icon name="logo-python" size="large"></ion-icon> in the beautiful city of Cape Town, South Africa, April 2020.
          </p>
        </div>

      </div>
    </footer>
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </html>