cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:print_id>', views.cart_add, name='cart_add'),
    path('remove/<str:print_id>', views.cart_remove, name='cart_remove'),
]

design_rox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf .urls.static import static
import print.views

admin.site.site_header = 'Designs By Rox Dicky Admin'
admin.site.site_title = 'Designs By Rox Dicky Admin'
admin.site.index_title = 'Designs By Rox Dicky Administration'



urlpatterns = [
    path('', print.views.home, name = 'home'),
    path('auth/', include('authenticate.urls', namespace='auth')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('print/', include('print.urls', namespace='print')),
    path('photo/', include('photo.urls')),
    path('wedding/', include('wedding.urls')),
    path('party/', include('party.urls')),
    path('business/', include('business.urls')),
    path('kid/', include('kid.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kid/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.kid, name = 'kid'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRINT_QUANITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddPrintForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRINT_QUANITY_CHOICES,
                                        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from print.models import Print
from .cart import Cart
from .forms import CartAddPrintForm

@require_POST
def cart_add(request, print_id):
    cart = Cart(request)
    print = get_object_or_404(Print, id=print_id)
    form = CartAddPrintForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(print=print,
                quantity=cd['quantity'],
                update_quantity=cd['update'])
        return redirect('cart:cart_detail')


def cart_remove(request, print_id):
    cart = Cart(request)
    print = get_object_or_404(Print, id=print_id)
    cart.remove(print)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddPrintForm(initial={'quantity': item['quantity'],
                                                        'update': True})

    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

{% load staticfiles %}

<h2>Your shopping cart</h2>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Print</th>
      <th>Qty</th>
      <th>Remove</th>
      <th>Unit Price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
    {% with print=item.print %}
    <tr>
      <td>
        <a href="{{ print.get_absolute_url }}">
          <img src="{% if print.image_tn %}{{ print.image_tn.url }}{% else %}{% static 'images/placeholder.png '%}{% endif %}" width="200px" class="img-thumbnail">
        </a>
      </td>
      <td>{{ print.name }}</td>
      <td>
        <form action="{% url 'cart:cart_add' print.id %}" method="post">
          {{ item.update_quantity_form.quantity }}
          {{ item.update_quantity_form.update }}
          <input type="submit" value="Update" class="btn btn-primary btn-sm">
          {% csrf_token %}
        </form>
      </td>
      <td><a href="{% url 'cart:cart_remove' print.id %}">Remove</a></td>
      <td>R {{ item.price }}</td>
      <td>R {{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr>
      <td>Total</td>
      <td colspan = "4"></td>
      <td>R {{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<p>
  <a href="{% url 'home' %}" class = "btn">Continue Shopping</a>
  <a href="{% url 'orders:order_create' %}">Checkout</a>

</p>

{% endblock %}